- name: 安装zsh (Linux)
  become: yes
  package:
    name: zsh
    state: present
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: 安装zsh (macOS)
  homebrew:
    name: zsh
    state: present
  when: ansible_os_family == 'Darwin'

- name: 下载oh-my-zsh安装脚本
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install-ohmyzsh.sh
    mode: 0755
  register: download_script
  changed_when: false # 总是执行以确保脚本最新

- name: 安装oh-my-zsh
  command: /tmp/install-ohmyzsh.sh --unattended
  args:
    creates: "{{ ansible_user_dir }}/.oh-my-zsh"
  environment:
    RUNZSH: "no"
  become: no
