- name: Install Linux tools
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ linux_tools }}"
  when:
    - ansible_os_family == 'Debian'
    - item in selected_tools|default(all_tools)

- name: Install Mac tools
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ mac_tools }}"
  when:
    - ansible_os_family == 'Darwin'
    - item in selected_tools|default(all_tools)
